services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: diad_api
    restart: unless-stopped
    command: npm run dev:api
    ports:
      - "3000:3000"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/node_modules

  worker:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: diad_worker
    restart: unless-stopped
    command: npm run dev:worker
    extra_hosts:
      - "host.docker.internal:host-gateway"
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/node_modules